version: '3.7'
services:

  kibana:
    image: kibana:7.6.2
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'

  elasticsearch:
    image: elasticsearch:7.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro


